### ISSUE TITLE
is rust bridge a project by the Rust Language Community Team?

### ISSUE THREAD

**Issue by skade** [rustbridge/website#36]
Just to have this logged:

"RustBridge is a project by the Rust Language Community Team."

I know this is from the old page. The intention back in the early meetings was for RustBridge to be a separate project, but we can take this up again.

**Comment by ashleygwilliams** [comment]
thanks for filing @skade - seems like this should be on the agenda for a rust community meeting

**Comment by skade** [comment]
So, I've got a little time, so some more words on it.

There's nothing strictly speaking pro and con this wording. I just want it to represent the real structure.

The reasoning in the initial kick-off meeting of RustBridge was that making RB somewhat attached to the community team might lead to people feeling the need to ask for community team consensus where just consensus in the RB team is needed. I tend to see most Rust teams as reporting to themselves and only getting other teams involved on need. If most of the RB team is somewhat involved in community, I can still see RB as a (mostly) subset, making the above statement true.

**Comment by ashleygwilliams** [comment]
thanks for the feedback @skade - in my experience, getting consistent and productive participation is the hardest part of organizing something like this. this is why i really like the idea of hitching it to a group that has a somewhat consistent membership and meeting schedule. while i agree that a rust bridge team shouldn't need to seek consensus from the community team on rust bridge matters, i also think that the rust bridge program could benefit from the structure being associated with such a team would supply.

is there a rust bridge team that is hosting events and meeting consistently that i am not aware of? i do see quite a few names listed on the previous site. (if this is the case please lemme know so that i can join these meetings and get more people collaborating on the site!)

**Comment by skade** [comment]
I do agree on that. There used to be a team with a consistent meeting schedule, but this has dissolved. As far as I remember, the original meeting was close to the community team meeting. The original team can be found here:

https://github.com/orgs/rust-community/teams/rustbridge/members

There's currently nothing structured happening, so any of that is up in the air.

**Comment by ashleygwilliams** [comment]
in the rust community team meeting this week we discussed this and decided that this project IS a rust community team project, but if it gets large enough we will revisit that question. closing.
